[package]
name = "nft-minter-deployer-meta"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.com>"]
edition = "2021"
publish = false
[dependencies.nft-minter-deployer]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.12.3"
